# Generated by Django 5.0.3 on 2024-05-08 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
