# Generated by Django 5.0.3 on 2024-05-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_rating_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='product_id',
            new_name='product',
        ),
    ]
